# Match Adwaita dark's terminal-like background instead of Kitty's default pure black.
enabled_layouts tall,grid

font_family SauceCodePro Nerd Font
background #1e1e1e
background_opacity 0.75
hide_window_decorations yes
scrollbar always
scrollbar_interactive yes
